create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  telephone text not null,
  email text not null,
  postcode text not null,
  blind_type text not null check (blind_type in (
    'Perfect Fit blinds',
    'Roller blinds',
    'Venetian blinds',
    'Vertical blinds',
    'Roman blinds',
    'Blackout blinds',
    'Made-to-measure blinds',
    'Not sure yet'
  )),
  number_of_windows integer not null check (number_of_windows between 1 and 100),
  preferred_date date not null,
  service_required text not null check (service_required in (
    'Free home measurement',
    'Free quote',
    'Both'
  )),
  message text check (message is null or char_length(message) <= 500),
  status text not null default 'New' check (status in (
    'New',
    'Contacted',
    'Measurement Booked',
    'Quote Sent',
    'Won',
    'Lost'
  )),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists enquiries_created_at_idx
  on public.enquiries (created_at desc);

create table if not exists public.lead_status_history (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.enquiries(id) on delete cascade,
  old_status text,
  new_status text not null,
  changed_at timestamptz not null default now(),
  changed_by text not null
);

create index if not exists lead_status_history_lead_id_changed_at_idx
  on public.lead_status_history (lead_id, changed_at desc);

create or replace function public.record_initial_enquiry_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.lead_status_history (lead_id, old_status, new_status, changed_by)
  values (new.id, null, new.status, 'System');
  return new;
end;
$$;

drop trigger if exists enquiries_initial_status_history on public.enquiries;
create trigger enquiries_initial_status_history
after insert on public.enquiries
for each row execute function public.record_initial_enquiry_status();

create or replace function public.update_enquiry_status(
  p_lead_id bigint,
  p_new_status text,
  p_changed_by text
)
returns setof public.enquiries
language plpgsql
security definer
set search_path = public
as $$
declare
  previous_status text;
begin
  if p_new_status not in ('New', 'Contacted', 'Measurement Booked', 'Quote Sent', 'Won', 'Lost') then
    raise exception 'Invalid enquiry status';
  end if;

  select status into previous_status
  from public.enquiries
  where id = p_lead_id
  for update;

  if not found then
    return;
  end if;

  if previous_status is distinct from p_new_status then
    update public.enquiries
    set status = p_new_status, updated_at = now()
    where id = p_lead_id;

    insert into public.lead_status_history (lead_id, old_status, new_status, changed_by)
    values (p_lead_id, previous_status, p_new_status, p_changed_by);
  end if;

  return query select * from public.enquiries where id = p_lead_id;
end;
$$;

insert into public.lead_status_history (lead_id, old_status, new_status, changed_by)
select id, null, status, 'System'
from public.enquiries
where not exists (
  select 1 from public.lead_status_history as history where history.lead_id = enquiries.id
);

revoke all on table public.lead_status_history from public, anon, authenticated;
revoke all on function public.update_enquiry_status(bigint, text, text) from public, anon, authenticated;
grant all on table public.lead_status_history to service_role;
grant usage, select on sequence public.lead_status_history_id_seq to service_role;
grant execute on function public.update_enquiry_status(bigint, text, text) to service_role;

create table if not exists public.enquiry_rate_limits (
  fingerprint text not null,
  window_start timestamptz not null,
  hit_count integer not null default 1,
  primary key (fingerprint, window_start)
);

create or replace function public.consume_enquiry_rate_limit(
  p_fingerprint text,
  p_limit integer default 5
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_window timestamptz;
  current_hits integer;
begin
  current_window := to_timestamp(floor(extract(epoch from now()) / 600) * 600);

  insert into public.enquiry_rate_limits (fingerprint, window_start)
  values (p_fingerprint, current_window)
  on conflict (fingerprint, window_start)
  do update set hit_count = enquiry_rate_limits.hit_count + 1
  returning hit_count into current_hits;

  return current_hits <= p_limit;
end;
$$;

revoke all on table public.enquiry_rate_limits from public, anon, authenticated;
revoke all on function public.consume_enquiry_rate_limit(text, integer) from public, anon, authenticated;
grant all on table public.enquiry_rate_limits to service_role;
grant execute on function public.consume_enquiry_rate_limit(text, integer) to service_role;

alter table public.enquiries enable row level security;
revoke all on table public.enquiries from anon, authenticated;
grant select, insert, update, delete on table public.enquiries to service_role;
grant usage, select on sequence public.enquiries_id_seq to service_role;