create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  telephone text not null,
  email text not null,
  postcode text not null,
  blind_type text not null check (blind_type in (
    'Perfect Fit blinds',
    'Roller blinds',
    'Venetian blinds',
    'Vertical blinds',
    'Roman blinds',
    'Blackout blinds',
    'Made-to-measure blinds',
    'Not sure yet'
  )),
  number_of_windows integer not null check (number_of_windows between 1 and 100),
  preferred_date date not null,
  service_required text not null check (service_required in (
    'Free home measurement',
    'Free quote',
    'Both'
  )),
  message text check (message is null or char_length(message) <= 500),
  status text not null default 'New' check (status in (
    'New',
    'Contacted',
    'Measurement Booked',
    'Quote Sent',
    'Won',
    'Lost'
  )),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists enquiries_created_at_idx
  on public.enquiries (created_at desc);

alter table public.enquiries enable row level security;
revoke all on table public.enquiries from anon, authenticated;
grant select, insert, update, delete on table public.enquiries to service_role;
grant usage, select on sequence public.enquiries_id_seq to service_role;